### ISSUE TITLE
Modify document-type-specific options that are not exposed via API

### ISSUE THREAD

**Issue by ChrisClems** [ChrisClems/EdgeSharp#13]
Config options like Flat Pattern Treatments to reduce bsplines to lines and arcs are not exposed via the API in any way. They're also saved at the document level so they cannot be bulk modified by changing defaults. We need a way to modify these options programmatically to operate on large sets of files.

Options are suspected to be stored in the PSMcluster0 stream in the COM structured storage of the document file.

[PSMcluster.zip](https://github.com/user-attachments/files/15916647/PSMcluster.zip)

[PSMclusterVariance.zip](https://github.com/user-attachments/files/15919060/PSMclusterVariance.zip)

[PSMcluster0-off.zip](https://github.com/user-attachments/files/15919058/PSMcluster0-off.zip)

**Comment by rmcanany** [comment]
@ChrisClems 
I ran across an old [post](https://community.sw.siemens.com/s/question/0D54O000061x030SAA/units-of-measuresproblem-solved-but-this-is-not-the-solution) on the SE Forum that used `SendKeys` to do something not exposed in the API.

It's far from ideal, but might be easier than hacking a binary stream in Windows Structured Storage.

**Comment by ChrisClems** [comment]
> @ChrisClems I ran across an old [post](https://community.sw.siemens.com/s/question/0D54O000061x030SAA/units-of-measuresproblem-solved-but-this-is-not-the-solution) on the SE Forum that used `SendKeys` to do something not exposed in the API.
> 
> It's far from ideal, but might be easier than hacking a binary stream in Windows Structured Storage.

Yeah, I hit some big dead ends with the structured storage streams. Every time I found something promising it would go nowhere without a deeper understanding of how the different streams appear to interact. Changing a simple value would change binary code all over the place. Saving a file with no changes would change far more in the binary than one would expect for simple timestamps, rev bump, etc. Maybe if I had a Parasolid SDK license I could poke around in the parasolid stream, but the x_b format is not documented and they're not even using simple x_b's for the parasolid. They're partitions and deltas which appear are individual parts of a complete x_b.

I think it's safe to close this as not planned for now. I'm at the end of my rope without spending a year or two studying reverse engineering and I'm in no hurry to go back to school.
